name: supplist-lite
description: Supplist Lite

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.1
  uuid: ^4.1.0
  intl: any
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  collection: ^1.18.0
  dropdown_search: ^5.0.6
  flutter_localizations:
    sdk: flutter
  url_launcher: ^6.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  build_runner: ^2.4.6
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/app_icon.png

flutter_icons:
  android: true
  ios: true
  image_path: "assets/app_icon.png"
